antora:
  extensions:
    - '@springio/antora-extensions/partial-build-extension'
    #- require: '@springio/antora-extensions/latest-version-extension'
    - require: '@springio/antora-extensions/inject-collector-cache-config-extension'
    - '@antora/collector-extension'
    - '@antora/atlas-extension'
    - require: '@springio/antora-extensions/root-component-extension'
      root_component_name: 'reactor-netty'
site:
  title: Component1
  url: https://pderop.github.io/test.reactor-netty/docs/reactor-netty/reference/
  #start_page: component1::inline-text-formatting.adoc
  #robots: allow
content:
  sources:
    - url: https://github.com/pderop/test.reactor-netty
      branches:
        - 'main'
      tags:
        - 'v1.1.*'
        - '!v1.1.{0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16}' # Exclude v1.1.[0-16]
        - '!v1.1.0(-{RC,M}*)' # Exclude v1.1.0-M1 and v1.1.0-RC*
      start_path: docs
asciidoc:
  attributes:
    page-stackoverflow-url: https://stackoverflow.com/tags/reactor-netty
    page-pagination: ''
    hide-uri-scheme: '@'
    tabs-sync-option: '@'
    chomp: 'all'
    toc2: true
  extensions:
    - '@asciidoctor/tabs'
    - '@springio/asciidoctor-extensions'
  sourcemap: true
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: ''
  redirect_facility: httpd
runtime:
  log:
    failure_level: warn
    format: pretty
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/v0.3.6/ui-bundle.zip
    #url: https://github.com/reactor/antora-ui-projectreactor/releases/download/latest/ui-bundle.zip
    snapshot: true
