name: build docs job

on:
  workflow_call:
    inputs:
      playbook:
        required: false
        type: string
        default: 'antora-playbook.yml'
      fetch-depth:
        required: false
        type: string
        default: '1'

jobs:
    build-antora:
        name: build-antora
        runs-on: ubuntu-20.04
        env:
            PLAYBOOK: ${{ inputs.playbook }}
            FETCH_DEPTH: ${{ inputs.fetch-depth }}
        steps:
            - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
              with:
                  fetch-depth: ${{ env.FETCH_DEPTH }}
            - name: Set up Ruby
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: 3.3.0
            - name: Install asciidoctor-pdf / rouge
              run: gem install asciidoctor-pdf rouge
            - uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93
              with:
                  distribution: 'temurin'
                  java-version: '17'
            - name: build antora
              run: ./gradlew antora -Pantora.playbook=${{ env.PLAYBOOK }}
            - name: Upload site
              uses: actions/upload-artifact@v4
              with:
                  name: doc
                  retention-days: 1
                  if-no-files-found: error
                  path: docs/build

