name: build branch doc job

on:
  workflow_call:
    inputs:
      output-artifact:
        required: true
        type: string

jobs:
    build:
        runs-on: ubuntu-20.04
        env:
            OUTPUT_ARTIFACT: ${{ inputs.output-artifact }}
        steps:
            - uses: actions/checkout@v4
            - name: Set up Ruby
              uses: ruby/setup-ruby@v1
              with:
                ruby-version: 3.3.0
            - name: Install asciidoctor-pdf / rouge
              run: gem install asciidoctor-pdf rouge
            - name: Setup java 17
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: '17'
            - name: Build antora
              run: ./gradlew antora
            - name: Copy the cache to be included in the site
              run: |-
                  [ -d docs/build/antora/inject-collector-cache-config-extension/.cache ] && cp -rf docs/build/antora/inject-collector-cache-config-extension/.cache docs/build/site/
            - name: Upload docs/build to output artifact
              uses: actions/upload-artifact@v3 # don't use v4, delete-artifact@v1 only supports v3 and delete-artifact@v2 does not support GHES
              with:
                  name: ${{ env.OUTPUT_ARTIFACT }}
                  retention-days: 1
                  if-no-files-found: error
                  path: docs/build

