name: delete old workflow runs
on:
    workflow_dispatch:
    schedule:
        - cron: '0 0 * * *'  # This cron schedule triggers the workflow every night at midnight (UTC time)

jobs:
    del_runs:
        runs-on: ubuntu-latest
        permissions:
            actions: write
            contents: read
        steps:
            - name: Delete workflow runs
              uses: Mattraks/delete-workflow-runs@v2
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  repository: ${{ github.repository }}
                  retain_days: 1
                  keep_minimum_runs: 3
