name: deploy docs job

on:
  workflow_call:
    inputs:
      full-version:
        required: true
        type: string
      version-type:
        required: true
        type: string
      component:
        required: true
        type: string

jobs:
  deploy-docs:
    name: deploy-docs
    runs-on: ubuntu-20.04
    env:
      FULL_VERSION: ${{ inputs.full-version }}
      VERSION_TYPE: ${{ inputs.version-type }}
      COMPONENT: ${{ inputs.component }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Download site
        uses: actions/download-artifact@v4
        with:
          name: site
          path: tmp
      - name: Download javadoc
        uses: actions/download-artifact@v4
        with:
            name: javadoc
            path: tmp
      - name: Prepare gh-pages
        run: |-
            mkdir gh-pages-docs
            > gh-pages-docs/.nojekyll
            mkdir -p gh-pages-docs/$COMPONENT/$FULL_VERSION/javadoc-api
            mkdir -p gh-pages-docs/$COMPONENT/$FULL_VERSION/reference/html
            mkdir -p gh-pages-docs/$COMPONENT/$FULL_VERSION/reference/pdf
            cp -r tmp/javadoc/* gh-pages-docs/$COMPONENT/$FULL_VERSION/javadoc-api/
            cp -r tmp/site/* gh-pages-docs/$COMPONENT/$FULL_VERSION/reference/html/
            if [ "$VERSION_TYPE" != "SNAPSHOT" ]; then
                pdf=$(find tmp/assembler -name "*.pdf" 2>/dev/null)
                [ -n "$pdf" ] && cp $pdf gh-pages-docs/$COMPONENT/$FULL_VERSION/reference/pdf/
            fi
      - name: Publish docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.DOCS_PAGES_TOKEN }}
          repository-name: pderop/test-antora-pages
          folder: gh-pages-docs
          target-folder: docs
          clean: false
          force: true



