name: build reference
run-name: ${{ format('{0} ({1})', github.workflow, github.event.inputs.build-refname || 'all') }}

on:
  workflow_dispatch:
    inputs:
      build-refname:
        description: Enter git refname to build (e.g., main, netty5). Leave empty for a full build.
        required: false

jobs:
  build-reference:
#    if: github.repository_owner == 'reactor'
    uses: ./.github/workflows/build-antora-job.yml
    with:
      build-refname: ${{ github.event.inputs.build-refname }}
      fetch-depth: 0
