name: deploy reference doc
run-name: ${{ format('{0} ({1})', github.workflow, github.event.inputs.build-refname || 'all') }}

on:
  workflow_dispatch:
    inputs:
      build-refname:
        description: Enter git refname to build (e.g., main, netty5). Leave empty for a full build.
        required: false

jobs:
  # build antora reference doc
  build-reference:
#    if: github.repository_owner == 'reactor'
    uses: ./.github/workflows/_build-doc.yml
    with:
      build-refname: ${{ github.event.inputs.build-refname }}
      fetch-depth: 0

  # deploy it to the site
  deploy-reference:
    needs: [ build-reference ]
    uses: ./.github/workflows/_deploy-doc.yml
    secrets: inherit
    with:
      component: netty

